# CodeRabbit configuration
# https://docs.coderabbit.ai/guides/configure-coderabbit

reviews:
  request_changes_workflow: true
  auto_review:
    enabled: false
    drafts: false
    ignore_usernames:
      - "dependabot[bot]"
  path_filters:
    - "!pnpm-lock.yaml"
    - "!package-lock.json"
    - "!package.json"
