import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const pkgPath = path.join(__dirname, '../package.json');
const destPath = path.join(__dirname, '../src/packageVersion.ts');

const { version } = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
const fileContent = `/**
 * 🤖 AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/embed-version.mjs from package.json
 */
/** Semver of this package. Use in logs or diagnostics to confirm the installed build. */
export const PLAYWRIGHT_SMART_TABLE_VERSION = ${JSON.stringify(version)} as const;
`;

fs.writeFileSync(destPath, fileContent);
console.log('✅ Version embedded into src/packageVersion.ts');
