import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// 1. Recreate __dirname for ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const srcPath = path.join(__dirname, '../src/types.ts');
const destPath = path.join(__dirname, '../src/typeContext.ts');

try {
  // 2. Read the source types
  let content = fs.readFileSync(srcPath, 'utf8');

  // 3. Clean up imports to reduce noise
  content = content.replace(/^import .*?;\n/gm, '').trim();

  // 4. Create the output file content
  const fileContent = `/**
 * 🤖 AUTO-GENERATED FILE. DO NOT EDIT.
 * This file is generated by scripts/embed-types.js
 * It contains the raw text of types.ts to provide context for LLM prompts.
 */
export const TYPE_CONTEXT = \`
${content}
\`;
`;

  // 5. Write to src/typeContext.ts
  fs.writeFileSync(destPath, fileContent);
  console.log('✅ Types successfully embedded into src/typeContext.ts');

} catch (e) {
  console.error('❌ Failed to embed types:', e);
  process.exit(1);
}