import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// 1. Recreate __dirname for ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const srcPath = path.join(__dirname, '../src/types.ts');
const destPath = path.join(__dirname, '../src/typeContext.ts');

try {
  // 2. Read the source types
  let content = fs.readFileSync(srcPath, 'utf8');

  // 3. Clean up imports to reduce noise
  content = content.replace(/^import .*?;\n/gm, '').trim();
  
  // 4. ESCAPE BACKTICKS (The Fix) 
  // We must escape backticks so they don't break the template literal in the output file.
  // We also escape ${ to prevent accidental interpolation if it appears in comments.
  content = content.replace(/\\/g, '\\\\')  // Escape backslashes first
                   .replace(/`/g, '\\`')     // Escape backticks
                   .replace(/\$\{/g, '\\${'); // Escape interpolation start

  // 5. Create the output file content
  const fileContent = `/**
 * 🤖 AUTO-GENERATED FILE. DO NOT EDIT.
 * This file is generated by scripts/embed-types.js
 * It contains the raw text of types.ts to provide context for LLM prompts.
 */
export const TYPE_CONTEXT = \`
${content}
\`;
`;

  // 6. Write to src/typeContext.ts
  fs.writeFileSync(destPath, fileContent);
  console.log('✅ Types successfully embedded into src/typeContext.ts');

} catch (e) {
  console.error('❌ Failed to embed types:', e);
  process.exit(1);
}