/**
 * 🤖 AUTO-GENERATED FILE. DO NOT EDIT.
 * This file is generated by scripts/embed-config-types.mjs
 * It contains minimal type definitions for config generation prompts.
 */
export const MINIMAL_CONFIG_CONTEXT = `
/**
 * Flexible selector type - can be a CSS string or function returning a Locator.
 * @example
 * // String selector
 * rowSelector: 'tbody tr'
 * 
 * // Function selector
 * rowSelector: (root) => root.locator('[role="row"]')
 */
export type Selector = string | ((root: Locator | Page) => Locator);

/**
 * Debug configuration for development and troubleshooting
 */
export type DebugConfig = {
  slow?: number | {
    pagination?: number;
    getCell?: number;
    findRow?: number;
    default?: number;
  };
  logLevel?: 'verbose' | 'info' | 'error' | 'none';
};

/**
 * Configuration options for useTable - focus on selectors and basic setup
 */
export interface TableConfig<T = any> {
  /** CSS selector or function for table headers */
  headerSelector?: string | ((root: Locator) => Locator);
  
  /** CSS selector or function for table rows */
  rowSelector?: string | ((root: Locator) => Locator);
  
  /** CSS selector or function for cells within a row */
  cellSelector?: string | ((row: Locator) => Locator);
  
  /** Transform header text (e.g., normalize, deduplicate) */
  headerTransformer?: (args: { 
    text: string; 
    index: number; 
    locator: Locator;
    seenHeaders: Set<string>;
  }) => string | Promise<string>;
  
  /** Automatically scroll to table on init (default: true) */
  autoScroll?: boolean;
  
  /** Debug options for development and troubleshooting */
  debug?: DebugConfig;
  
  /** Advanced: Custom strategies for pagination, sorting, navigation, etc. */
  strategies?: TableStrategies;
  
  /** Custom data mappers for extracting complex types (boolean, number) */
  dataMapper?: Partial<Record<keyof T, (cell: Locator) => Promise<T[keyof T]> | T[keyof T]>>;
}

/**
 * Example usage:
 */
// const table = useTable(page.locator('table'), {
//   headerSelector: 'thead th',
//   rowSelector: 'tbody tr',
//   cellSelector: 'td',
//   headerTransformer: ({ text }) => text.trim()
// });

`;
