/**
 * 🤖 AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by scripts/embed-version.mjs from package.json
 */
/** Semver of this package. Use in logs or diagnostics to confirm the installed build. */
export const PLAYWRIGHT_SMART_TABLE_VERSION = "6.11.0" as const;
