#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🚧 Running build and docs generation..."
npm run build

# Check if any tracked files were modified by the build
if [ -n "$(git status --porcelain)" ]; then
  echo "❌ Error: The build/docs generation modified files."
  echo "   Please commit these changes and try pushing again."
  echo ""
  git status --short
  exit 1
fi

echo "✅ Build clean. Pushing..."